### ISSUE TITLE
Automation of monthly email

### ISSUE THREAD

**Issue by aljachimiak** [hvopen/hvopen-website#6]
The [monthly meeting email](https://github.com/hvopen/hvopen-html-email-meetings) was constructed in such a manner that the fields could be populated in a scripted manner.

The list of unique identifiers for the template are maintained in the email src for convenience:

https://github.com/hvopen/hvopen-html-email-meetings/blob/ead520ae4f903fc66ab64e5d06a9bf3693be07a2/src/pages/monthly-meeting.html#L208-L225

Some notes off the top of my head:
- this will be a command line tool stored in the `/tools` dir of this repo
- written in python with requirements [stored in this file](https://github.com/hvopen/hvopen-website/blob/master/requirements_dev.txt)
- will use the Mail chimp api to create a new campaign from the template for the monthly email
- api keys will be stored in the env
- most of the unique identifier fields will be pulled from the file for the event that is going to be emailed.

Any further thoughts @sdague ?

**Comment by sdague** [comment]
It's done!
